### PR TITLE
Load _glynn.yml before setting ftp config vars

### LINKED ISSUE #52: No connection. Digitalocean host
Connected to server. Sending site
/Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Connection refused - connect(2) for "maukasta.fi" port 21 (Errno::ECONNREFUSED)
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:133:in `new'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:133:in `open'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.2/lib/glynn/ftp.rb:23:in `connect'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.2/lib/glynn/ftp.rb:16:in `sync'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/glynn-1.2.2/bin/glynn:88:in `<top (required)>'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/bin/glynn:23:in `load'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/bin/glynn:23:in `<main>'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

My setting are _glynn.yml
ftp_host: 'maukasta.fi'
ftp_dir: '/var/www/maukasta.fi/public_html/' 
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'root'     # default read from stdin
ftp_password: '....' # default read from stdin
ftp_secure: true              # default false

But why console says ftp secure false?

### PR DESCRIPTION
**Pull request by dmathieu**
Closes #52 
cc @vjandrei

### CODE REVIEW

**Comment by vjandrei** [comment]
Great, I will check it.

**Comment by dmathieu** [comment]
You can use it directly. I've just released v1.2.3.

**Comment by vjandrei** [comment]
Mathieu why to console says still 
Successfully generated site
Sending site over FTP (host: maukasta.fi, port: 22, ftps: true)
Connected to server. Sending site
/Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:83:in `initialize': Connection refused - connect(2) for "maukasta.fi" port 21 (Errno::ECONNREFUSED)

I have but port 22 but it will show port 21 ECONNREFUSED ? 
I have test the connection other ftp clients and it works fine? What I miss here.

**Comment by dmathieu** [comment]
That's definitely strange, as it would appear we're properly using port 22.

> Sending site over FTP (host: maukasta.fi, port: **22**, ftps: true)

That could be a bug in the [DoubleBagFTPS](https://github.com/bnix/double-bag-ftps) library. Could you try disabling `ftp_secure`?

**Comment by vjandrei** [comment]
Now I had ftp_secure: false and port 22 but still
/Users/andreaskoutsoukos/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Connection refused - connect(2) for "maukasta.fi" port 21 (Errno::ECONNREFUSED)

**Comment by dmathieu** [comment]
Could you try explicitely passing an active connection?

```
ftp_passive: false
```

It looks like this happens when DoubleBagFTPS calls [open_socket](https://github.com/bnix/double-bag-ftps/blob/master/lib/double_bag_ftps.rb#L102), for which the host/port are set with [makepasv](https://github.com/bnix/double-bag-ftps/blob/master/lib/double_bag_ftps.rb#L94) which itself is [in Net::FTP](http://ruby-doc.org/stdlib-1.9.3/libdoc/net/ftp/rdoc/Net/FTP.html#method-i-sendcmd).
An invalid port here seems to indicate your FTP server itself returned 21 as the required port.

Using an active connection might solve your issue.

**Pull request merged**
